2024-08-28 16:34:26,282 ERROR: Error occurred: Expecting property name enclosed in double quotes: line 1 column 69 (char 68) [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-28 16:37:04,445 ERROR: Error occurred: Filter not allowed on one of the specified keys. [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-28 16:37:45,369 ERROR: SQLAlchemy error occurred: IN expression list, SELECT construct, or bound parameter object expected, got '[7]'. [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:60]
2024-08-28 16:37:45,370 ERROR: Error occurred: IN expression list, SELECT construct, or bound parameter object expected, got '[7]'. [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-28 16:38:49,026 ERROR: SQLAlchemy error occurred: Column expression, FROM clause, or other columns clause element expected, got <class 'telegram._bot.Bot'>. [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:60]
2024-08-28 16:38:49,027 ERROR: SQLAlchemy error occurred: Column expression, FROM clause, or other columns clause element expected, got <class 'telegram._bot.Bot'>. [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:60]
2024-08-28 16:38:49,028 ERROR: Error occurred: Column expression, FROM clause, or other columns clause element expected, got <class 'telegram._bot.Bot'>. [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-28 16:39:40,525 ERROR: Error occurred: name 'Bot' is not defined [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-28 16:39:40,525 ERROR: Error occurred: name 'Bot' is not defined [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-28 16:39:40,525 ERROR: Error occurred: name 'Bot' is not defined [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-28 17:21:25,005 ERROR: Error occurred: No Merchants To Show [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-29 09:09:39,089 ERROR: Error occurred: name 'se' is not defined [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-29 09:09:39,090 ERROR: Error occurred: name 'se' is not defined [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-29 12:48:39,522 ERROR: Error occurred: 'ActivityMaster' object has no attribute 'activity_name' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-29 12:48:39,523 ERROR: Error occurred: 'ActivityMaster' object has no attribute 'activity_name' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-29 12:48:39,523 ERROR: Error occurred: 'ActivityMaster' object has no attribute 'activity_name' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-29 16:55:16,402 ERROR: Error occurred: to_dict() got an unexpected keyword argument 'propagation' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-29 16:55:16,403 ERROR: Error occurred: to_dict() got an unexpected keyword argument 'propagation' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-29 16:59:19,394 ERROR: Error occurred: to_dict() got an unexpected keyword argument 'propagation' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-29 16:59:19,395 ERROR: Error occurred: to_dict() got an unexpected keyword argument 'propagation' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-29 17:46:09,204 ERROR: Error occurred: Filter not allowed on one of the specified keys. [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-29 17:46:21,115 ERROR: Error occurred: Filter not allowed on one of the specified keys. [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-29 17:46:24,587 ERROR: Error occurred: Filter not allowed on one of the specified keys. [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-29 17:46:52,735 ERROR: Error occurred: Filter not allowed on one of the specified keys. [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-29 17:47:56,389 ERROR: Error occurred: Filter not allowed on one of the specified keys. [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-30 09:11:38,954 ERROR: Error occurred: Error 61 connecting to localhost:6379. Connection refused. [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-30 09:12:20,287 ERROR: Error occurred: start_bot() got an unexpected keyword argument 'id' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-30 13:28:43,094 ERROR: Error occurred: Merchant Not Mapped To This Group [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-30 13:29:13,824 ERROR: Error occurred: Merchant Not Mapped To This Group [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-30 13:29:22,429 ERROR: Error occurred: Merchant Not Mapped To This Group [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-30 13:30:51,141 ERROR: Error occurred: Merchant Not Mapped To This Group [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-31 10:46:19,506 ERROR: Error occurred: No active exception to reraise [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-31 10:47:23,487 ERROR: Error occurred: No active exception to reraise [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-31 10:51:03,394 ERROR: Error occurred: activity already assigned to role [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-08-31 10:51:05,610 ERROR: Error occurred: activity already assigned to role [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 11:16:15,937 ERROR: Error occurred: Not Added - Some Error Occured [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 11:17:37,624 ERROR: Error occurred: Not Added - Some Error Occured [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 11:18:46,368 ERROR: Error occurred: No active exception to reraise [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 11:19:00,235 ERROR: Error occurred: Not Added - Some Error Occured [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 11:19:20,424 ERROR: Error occurred: Not Added - Some Error Occured [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 11:23:06,662 ERROR: Error occurred: Bot Not Found [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 11:58:58,223 ERROR: Error occurred: 'str' object has no attribute 'items' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 12:02:00,273 ERROR: Error occurred: 'str' object has no attribute 'items' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 12:05:12,608 ERROR: Error occurred: 'str' object has no attribute 'items' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 12:06:49,638 ERROR: Error occurred: 'str' object has no attribute 'items' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 12:09:24,805 ERROR: Error occurred: 'str' object has no attribute 'items' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 12:10:06,403 ERROR: Error occurred: 'str' object has no attribute 'items' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 12:11:41,577 ERROR: Error occurred: 'NoneType' object has no attribute 'bot_id' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 12:16:06,736 ERROR: Error occurred: local variable 'headers' referenced before assignment [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 12:16:57,695 ERROR: Error occurred: No active exception to reraise [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 12:17:59,030 ERROR: Error occurred: No active exception to reraise [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 12:18:57,689 ERROR: Error occurred: 'int' object is not iterable [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 12:19:20,950 ERROR: Error occurred: 'int' object is not iterable [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 12:19:37,646 ERROR: Error occurred: 'int' object is not iterable [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 12:20:00,689 ERROR: Error occurred: 'list' object has no attribute 'items' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
