2024-09-05 11:18:53,135 ERROR: Error occurred: Invalid URL 'VwiJ294dhwij2919292ndunwdWnshfB992cW120WHkdsuccess_rate_account.php': No scheme supplied. Perhaps you meant https://VwiJ294dhwij2919292ndunwdWnshfB992cW120WHkdsuccess_rate_account.php? [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-05 11:18:53,137 ERROR: Error occurred: Invalid URL 'VwiJ294dhwij2919292ndunwdWnshfB992cW120WHkdsuccess_rate_account.php': No scheme supplied. Perhaps you meant https://VwiJ294dhwij2919292ndunwdWnshfB992cW120WHkdsuccess_rate_account.php? [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-05 15:29:51,347 ERROR: Error occurred: notice_function() missing 2 required positional arguments: 'update' and 'context' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-06 10:59:44,633 ERROR: Error occurred: Object of type set is not JSON serializable [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-06 11:00:22,937 ERROR: Error occurred: Object of type generator is not JSON serializable [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-06 17:07:19,410 ERROR: Error occurred: Expecting value: line 1 column 1 (char 0) [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-06 17:07:19,411 ERROR: Error occurred: Expecting value: line 1 column 1 (char 0) [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-06 17:07:43,629 ERROR: Error occurred: 'str' object has no attribute 'read' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-06 17:07:43,630 ERROR: Error occurred: 'str' object has no attribute 'read' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-06 17:08:28,389 ERROR: Error occurred: 'str' object has no attribute 'read' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-06 17:08:28,390 ERROR: Error occurred: 'str' object has no attribute 'read' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-06 17:09:08,413 ERROR: Error occurred: Expecting value: line 1 column 1 (char 0) [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-06 17:09:08,414 ERROR: Error occurred: Expecting value: line 1 column 1 (char 0) [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-07 08:48:23,294 ERROR: Error occurred: local variable 'formatted_msg' referenced before assignment [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-09 09:30:06,708 ERROR: Error occurred: Object '<Events at 0x7fa91a9f0880>' is already attached to session '3' (this is '4') [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-09 12:20:01,758 ERROR: Error occurred: '<=' not supported between instances of 'int' and 'str' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-09 12:20:01,760 ERROR: Error occurred: '<=' not supported between instances of 'int' and 'str' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-09 12:20:35,668 ERROR: Error occurred: invalid literal for int() with base 10: '91.66666666666666' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-09 12:20:35,668 ERROR: Error occurred: invalid literal for int() with base 10: '91.66666666666666' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-09 12:21:21,599 ERROR: Error occurred: '<=' not supported between instances of 'int' and 'str' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-09 12:21:21,600 ERROR: Error occurred: '<=' not supported between instances of 'int' and 'str' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-09 12:21:53,956 ERROR: Error occurred: '<=' not supported between instances of 'int' and 'str' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-09 12:21:53,957 ERROR: Error occurred: '<=' not supported between instances of 'int' and 'str' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-09 12:22:18,461 ERROR: Error occurred: invalid literal for int() with base 10: '91.66666666666666' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-09 12:22:18,461 ERROR: Error occurred: invalid literal for int() with base 10: '91.66666666666666' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-09 12:23:12,215 ERROR: Error occurred: type str doesn't define __round__ method [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-09 12:23:12,215 ERROR: Error occurred: type str doesn't define __round__ method [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-09 12:23:27,707 ERROR: Error occurred: local variable 'val' referenced before assignment [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-09 12:23:27,707 ERROR: Error occurred: local variable 'val' referenced before assignment [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-09 12:24:18,060 ERROR: Error occurred: invalid literal for int() with base 10: '91.66666666666666' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-09 12:24:18,060 ERROR: Error occurred: invalid literal for int() with base 10: '91.66666666666666' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-09 12:28:14,564 ERROR: Error occurred: beautify_daily_collection() got multiple values for argument 'data' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-09 12:28:14,564 ERROR: Error occurred: beautify_daily_collection() got multiple values for argument 'data' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
